version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y tar gzip

  pre_build:
    commands:
      - echo "Starting pre-build step..."

  build:
    commands:
      - echo "Running build step..."
      # لو عندك app (مثلاً Node.js أو React) هنا بتحط أوامر build
      # npm install && npm run build

  post_build:
    commands:
      - echo "Post-build step complete."

artifacts:
  files:
    - "**/*"
  discard-paths: no
